ci: preguntando cuál es la rama principal de sonar

diff --git a/.github/workflows/develop_pipeline.yml b/.github/workflows/develop_pipeline.yml
--- a/.github/workflows/develop_pipeline.yml
+++ b/.github/workflows/develop_pipeline.yml
@@ -26,13 +26,20 @@ jobs:
           set +e
           # Considerar usar siempre comillas dobles. Si no funciona probar cambiando el nombre del proyecto (name y project deben ser iguales siempre)
           curl -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/projects/create" -d "name=laboratorio-final-" -d "project=laboratorio-final-" -d "organization=jcaresdiplomado" -d "visibility=public" -d "branch=develop" -d "mainBranch=develop"
-          curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/list" -d "project=laboratorio-final-"
 
           if [ $? -ne 0 ]; then
             echo "El proyecto laboratorio-final ya existe, nos saltamos la creación."
           else
             echo "Proyecto laboratorio-final creado exitosamente en SonarQube Cloud."
             # echo "Estableciendo rama develop como principal."
-            curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/rename" -d "branch=develop" -d "project=laboratorio-final-"
+            # curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/rename" -d "branch=develop" -d "project=laboratorio-final-" -d "name=laboratorio-final-"
+          fi
+          # Ahora elegimos la rama develop como principal si es que no es
+          #  aa
+          # Ejemplo de salida del curl consultando las ramas:{"branches":[{"name":"master","isMain":true,"type":"LONG","branchId":"b2a7126f-0fdf-4697-8aea-b7e18b793287","branchUuidV1":"AZexjqe1mn08eUWmbf6z"}]}
+          MAIN_BRANCH=$(curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/list" -d "project=laboratorio-final-" | jq -r '.branches[] | select(.isMain == true) | .name')
+          if [ "$MAIN_BRANCH" != "develop" ]; then
+            echo "Error: La rama principal no es 'develop', es '$MAIN_BRANCH'."
+            exit 1
           fi
           set -e
